port: 8000
portTls: 8443
basePath: "./blog/public"
defaultDocuments:
  - index.html
cgiEndpoints:
  - pathElement: api
    cgiPath: dotnet
    cgiArguments: "MAC\\src\\MAC\\bin\\Debug\\netcoreapp1.0\\publish\\MAC.dll"
  - pathElement: env
    cgiPath: printenv