# purpose of this file:
# This is an example SQL table generated by the MAC
# using a ruby program to parse the file titled example_models.yaml
# a javascript class is also generated from the same program

CREATE TABLE USERS(
  ID        INT         NOT NULL,
  PASSWORD  VARCHAR(64) NOT NULL,
  CITY      VARCHAR(30) NOT NULL,
  FULLNAME  VARCHAR(30) NOT NULL,
  CREATEDAT DATETIME    NOT NULL,
  UPDATEDAT DATETIME    NOT NULL,
  PRIMARY KEY (ID)
)

#screensketch by Matthew Slane