-
  name: post
  fields:
    -
      name: Title
      type: string
      validations:
        required: true
    -
      name: Body
      type: string
    -
      name: PublishedAt
      type: DateTime

-
  name: comment
  fields:
    -
      name: FullName
      type: string
      validations:
        required: true
    -
      name: Email
      type: Mac.User.Email
      validations:
        required: true
    -
      name: Website
      type: Url

    -
      name: Body
      type: string
      validations:
        required: true

-
  name: post_ownership
  fields:
    -
      name: post
      relationship: true
      table: post
      unique: true
    -
      name: user
      relationship: true
      table: user
      unique: false
